target := "riscv64gc-unknown-none-elf"
mode := "release"
kernel_elf := f'target/{{target}}/{{mode}}/os'
kernel_bin := f'{{kernel_elf}}.bin'
fs_img := f'../user/target/{{target}}/{{mode}}/fs.img'
apps := "../user/src/bin/"
bootloader := "../bootloader/rustsbi-qemu.bin"
kernel_entry_pa := "0x80200000"
objcopy := "rust-objcopy --binary-architecture=riscv64"
qemu_name := "qemu-system-riscv64"
qemu_args := f'-machine virt \
               -nographic \
               -bios {{bootloader}} \
               -device loader,file={{kernel_bin}},addr={{kernel_entry_pa}} \
               -drive file={{fs_img}},if=none,format=raw,id=x0 \
               -device virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0'

default: build

kernel:
    @cd ../user && just build
    @cargo build --{{mode}}

kernel_bin: kernel
    @{{objcopy}} {{kernel_elf}} --strip-all -O binary {{kernel_bin}}

fs-img:
    @cd ../user && just build 
    @rm -f {{fs_img}}
    @cd ../easy-fs-fuse && cargo run --release -- -s {{apps}} -t ../user/target/{{target}}/{{mode}}/

build: kernel_bin fs-img

run: build
    @{{qemu_name}} {{qemu_args}}

gdb-server: build
    @{{qemu_name}} {{qemu_args}} -s -S

gdb-client:
    @riscv64-unknown-elf-gdb \
        -ex 'file target/riscv64gc-unknown-none-elf/release/os' \
        -ex 'set arch riscv:rv64' \
        -ex 'target remote localhost:1234'

clean:
    @cd ../user && cargo clean
    @cargo clean
